# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.


In [100]:
import numpy as np

# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array) 

# Replace all the elements in the third column with 1
array[:, 2] = 1
print("Modified array:")
print(array)

Original array:
[[10  9 13  3  5]
 [10 13 18  1  3]
 [ 5 19  6  3 15]
 [13 13  6 17 19]
 [ 9  2  5 13  4]]
Modified array:
[[10  9  1  3  5]
 [10 13  1  1  3]
 [ 5 19  1  3 15]
 [13 13  1 17 19]
 [ 9  2  1 13  4]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.


In [101]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16
import numpy as np 
arr=np.random.randint(1,16 ,(4,4))
print("random array")
print(arr)
# Replace the diagonal elements with 0
print("modified array")
np.fill_diagonal(arr,0)
print(arr)

random array
[[10 13  1 11]
 [ 7 14  1  3]
 [ 6 10  8  3]
 [13  1  3  5]]
modified array
[[ 0 13  1 11]
 [ 7  0  1  3]
 [ 6 10  0  3]
 [13  1  3  0]]



### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.


In [102]:
# Create a NumPy array of shape (6, 6) with values from 1 to 36
array = np.arange(1, 37).reshape((6, 6))
print("Original array:")
print(array)

# Extract the sub-array
sub_array = array[2:5, 1:4]
print("Sub-array:")
print(sub_array)

Original array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub-array:
[[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.


In [103]:
# Create a NumPy array of shape (5, 5) with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Extract the elements on the border
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements:")
print(border_elements)

Original array:
[[ 3  7  6 14 18]
 [ 5 15 12 13 17]
 [17 10  9  5 13]
 [ 7  2  6  4 10]
 [19  3  6 13 10]]
Border elements:
[ 3  7  6 14 18 19  3  6 13 10  5 17  7 17 13 10]



### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.


In [104]:
# Create two NumPy arrays of shape (3, 4) filled with random integers
array1 = np.random.randint(1, 11, size=(3, 4))
array2 = np.random.randint(1, 11, size=(3, 4))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)

Array 1:
[[ 8  9  5  4]
 [10  1  9  8]
 [ 7  4  2  9]]
Array 2:
[[10  5  9  1]
 [ 4  3  8  3]
 [ 7  9  6  8]]
Element-wise addition:
[[18 14 14  5]
 [14  4 17 11]
 [14 13  8 17]]
Element-wise subtraction:
[[-2  4 -4  3]
 [ 6 -2  1  5]
 [ 0 -5 -4  1]]
Element-wise multiplication:
[[80 45 45  4]
 [40  3 72 24]
 [49 36 12 72]]
Element-wise division:
[[0.8        1.8        0.55555556 4.        ]
 [2.5        0.33333333 1.125      2.66666667]
 [1.         0.44444444 0.33333333 1.125     ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.


In [105]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16
array = np.arange(1, 17).reshape((4, 4))
print("Original array:")
print(array)

# Compute the row-wise and column-wise sum
row_sum = np.sum(array, axis=1)
column_sum = np.sum(array, axis=0)

print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(column_sum)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum:
[10 26 42 58]
Column-wise sum:
[28 32 36 40]



### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.



In [106]:
arr=np.random.randint(1,30 ,(5,5))
print(arr)
#Compute the mean, median, standard deviation, and variance
mean=np.mean(arr)
median=np.median(arr)
variance=np.var(arr)
standard_division=np.std(arr)

#print all the statistical values
print("mean:",mean)
print("median:",median)
print("standard_division :",standard_division)
print("variance:",variance)

[[ 3 21  6  1 29]
 [26 16 22 10 11]
 [ 3 13 25 16 15]
 [20 15  8 27  9]
 [12 17 11 24 10]]
mean: 14.8
median: 15.0
standard_division : 7.751128950030441
variance: 60.08


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).


In [107]:
arr=np.random.randint(1,9 ,(3,3))
print("original array\n",arr)
#Compute the mean and  standard deviation
mean=np.mean(arr)
standard_division=np.std(arr)
#normalize array
normalized_array=(arr-mean)/standard_division
print("Normalize array \n",normalized_array)

original array
 [[4 7 1]
 [5 1 8]
 [2 7 2]]
Normalize array 
 [[-0.04271788  1.11066496 -1.19610072]
 [ 0.34174306 -1.19610072  1.4951259 ]
 [-0.81163977  1.11066496 -0.81163977]]



### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [108]:
# Create a NumPy array of shape (3, 3) filled with random integers
array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)

# Add the 1D array to each row of the 2D array using broadcasting
result = array + row_array
print("Resulting array:")
print(result)

Original array:
[[6 5 4]
 [4 7 4]
 [3 7 6]]
1D array:
[ 6 10  1]
Resulting array:
[[12 15  5]
 [10 17  5]
 [ 9 17  7]]





2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.


In [109]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 11, size=(4, 4))
column_array = np.random.randint(1, 11, size=(4,))
print("Original array:")
print(array)
print("1D array:")
print(column_array)

# Subtract the 1D array from each column of the 2D array using broadcasting
result = array - column_array[:, np.newaxis]
print("Resulting array:")
print(result)

Original array:
[[ 9  7  5  3]
 [ 2 10  9  7]
 [ 8  4  1  2]
 [ 4  4  6 10]]
1D array:
[2 4 7 6]
Resulting array:
[[ 7  5  3  1]
 [-2  6  5  3]
 [ 1 -3 -6 -5]
 [-2 -2  0  4]]



### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.


In [110]:
# Create a NumPy array of shape (3, 3) representing a matrix
matrix = np.random.randint(1, 11, size=(3, 3))
print("Original matrix:")
print(matrix)

# Compute the determinant
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

# Compute the inverse
inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)

Original matrix:
[[5 3 9]
 [2 6 3]
 [7 2 3]]
Determinant: -237.00000000000009
Inverse:
[[-0.05063291 -0.03797468  0.18987342]
 [-0.06329114  0.20253165 -0.01265823]
 [ 0.16033755 -0.0464135  -0.10126582]]
Eigenvalues: [13.60113503 -3.97965709  4.37852206]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.


In [111]:
# Create two NumPy arrays of shape (2, 3) and (3, 2)
array1 = np.random.randint(1, 11, size=(2, 3))
array2 = np.random.randint(1, 11, size=(3, 2))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform matrix multiplication
result = np.dot(array1, array2)
print("Matrix multiplication result:")
print(result)

Array 1:
[[ 2  4 10]
 [ 1  6  2]]
Array 2:
[[4 1]
 [5 1]
 [2 6]]
Matrix multiplication result:
[[48 66]
 [38 19]]



### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).


In [112]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

# Reshape the array to shape (1, 9)
reshaped_array_1 = array.reshape((1, 9))
print("Reshaped array (1, 9):")
print(reshaped_array_1)

# Reshape the array to shape (9, 1)
reshaped_array_2 = reshaped_array_1.reshape((9, 1))
print("Reshaped array (9, 1):")
print(reshaped_array_2)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped array (1, 9):
[[1 2 3 4 5 6 7 8 9]]
Reshaped array (9, 1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).


In [113]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Flatten the array
flattened_array = array.flatten()
print("Flattened array:")
print(flattened_array)

# Reshape the array back to (5, 5)
reshaped_array = flattened_array.reshape((5, 5))
print("Reshaped array:")
print(reshaped_array)

Original array:
[[19 18 17 10  8]
 [ 2  7 14  8 15]
 [19  9  9 16  8]
 [19 20  6  9 17]
 [12  9  3 11 13]]
Flattened array:
[19 18 17 10  8  2  7 14  8 15 19  9  9 16  8 19 20  6  9 17 12  9  3 11
 13]
Reshaped array:
[[19 18 17 10  8]
 [ 2  7 14  8 15]
 [19  9  9 16  8]
 [19 20  6  9 17]
 [12  9  3 11 13]]



### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.


In [114]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, (5, 5))
print("Original array:")
print(array)

# Use fancy indexing to extract the elements at the corners of the array
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)

Original array:
[[14  4 11  9 14]
 [ 1  5 13  3  7]
 [10 19 16 14 13]
 [ 9  6  4  7 14]
 [15 17 17  1 14]]
Corner elements:
[14 14 15 14]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.


In [115]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(array)

# Use boolean indexing to set all elements greater than 10 to 10
array[array > 10] = 10
print("Modified array:")
print(array)

Original array:
[[18  3 13  8]
 [ 9 12 15 13]
 [19  2  4 18]
 [17 19 15  9]]
Modified array:
[[10  3 10  8]
 [ 9 10 10 10]
 [10  2  4 10]
 [10 10 10  9]]



### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.


In [116]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.


In [117]:
# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]



### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.


In [118]:
import numpy.ma as ma

# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[16 15  2 20]
 [10 16 15 19]
 [16  7  3 17]
 [17  1 10  7]]
Masked array:
[[-- -- 2 --]
 [10 -- -- --]
 [-- 7 3 --]
 [-- 1 10 7]]
Sum of unmasked elements: 40


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [119]:
# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[14  7  1]
 [ 8  3 13]
 [ 4 12 11]]
Masked array:
[[-- 7 1]
 [8 -- 13]
 [4 12 --]]
Modified masked array:
[[ 7  7  1]
 [ 8  7 13]
 [ 4 12  7]]
